config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/privacy_policy', to: 'home#privacy_policy'
  get 'home/terms_of_service', to: 'home#terms_of_service'

  get 'line_login_api/login', to: 'line_login_api#login'
  get 'line_login_api/callback', to: 'line_login_api#callback'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "study_time/index" => "study_time#index"
  get 'answer_index/index' => 'answer_index#index'

  get "login" => "login#login"
  delete 'logout', to: 'setting#destroy', as: 'logout'

  # ゲストログイン
  post 'guest_login', to: 'login#guest_login'

  # LINE_message
  post 'send_custom_message', to: 'messages#send_custom_message'

  # get '/study_records' => 'study_records#index'
  resources :study_records, only: [:index] do
    member do
      patch :stop
    end
    collection do
      post :start
    end
  end
  resources :answers, only: [:new, :create]

    # カスタムエラーページ用のルート
    get '/400', to: 'errors#bad_request', as: :bad_request
    get '/401', to: 'errors#unauthorized', as: :unauthorized
    get '/403', to: 'errors#forbidden', as: :forbidden
    get '/404', to: 'errors#not_found', as: :not_found
    get '/409', to: 'errors#conflict', as: :conflict
    get '/422', to: 'errors#unprocessable_entity', as: :unprocessable_entity
    get '/429', to: 'errors#too_many_requests', as: :too_many_requests
    get '/500', to: 'errors#internal_server_error', as: :internal_server_error
    get '/503', to: 'errors#service_unavailable', as: :service_unavailable

  # すべての未知ルートを404
  match '*path', to: 'errors#not_found', via: :all

  # 開発環境でのみエラーページのプレビューを有効にする
  if Rails.env.development?
    get '/errors/:status', to: 'errors#show'
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  enum first_answer_choice: { study: 1, break: 2, other: 3 }

  validates :user_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/study_record.rb
class StudyRecord < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :answers
  has_many :study_records

  validates :line_user_id, presence: true, uniqueness: true
  validates :name, presence: true

  def self.guest
    find_or_create_by!(line_user_id: 'lis12345') do |user|
      user.name = "guest"
      user.is_guest = true
    end
  end 

  def guest?
    self.is_guest
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = initialize_answer_from_session
  end

  def create
    session[:answers] ||= {}
    session[:answers].merge!(answer_params.to_h)

    @answer = initialize_answer_from_session

    if @answer.valid?
      if final_question_answered?(@answer)
        @answer.save
        session.delete(:answers)
        render_final_message
      else
        @next_question = determine_next_question(@answer)
        render_next_question
      end
    else
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace("question_area", partial: "answers/form", locals: { answer: @answer }) }
        format.html { render :new }
      end
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:first_answer_choice, :second_answer, :third_answer)
  end

  def initialize_answer_from_session
    current_user.answers.build(session[:answers] || {})
  end

  def determine_next_question(answer)
    case answer.first_answer_choice
    when "study"
      if answer.second_answer.present?
        "それをする事で何を得ますか？"
      else
        "何の勉強をしていますか？"
      end
    when "break"
      "あと何分休憩しますか？"
    when "other"
      if answer.second_answer.present?
        "それをしたら何を失いますか？"
      else
        "何をしていますか？"
      end
    end
  end

  def render_next_question
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.update("question_area", partial: "answers/next_question", locals: { next_question: @next_question }) }
    end
  end

  def final_question_answered?(answer)
    p "final_question_answered?"
    case answer.first_answer_choice
    when 'study'
      answer.third_answer.present? # 「勉強」が選ばれた場合、third_answerが最後の質問になる
    when 'break'
      answer.second_answer.present? # 「休憩」が選ばれた場合、second_answerが最後の質問になる
    when 'other'
      answer.third_answer.present? # 「その他」が選ばれた場合、third_answerが最後の質問になる
    else
      false # それ以外の場合は、まだ最後の質問に到達していない
    end
  end

  def render_final_message
    respond_to do |format|
      format.turbo_stream do
        # 'question_area'を新しいフォームで置き換える
        render turbo_stream: turbo_stream.replace("question_area", partial: "answers/final_message")
      end
    end
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  layout 'error'

  def show
    status_code = params[:status] || 500
    render template: "errors/#{status_code}", status: status_code, layout: 'error'
  end

  def bad_request
    render(status: 400)
  end

  def unauthorized
    render(status: 401)
  end

  def forbidden
    render(status: 403)
  end

  def not_found
    render(status: 404)
  end

  def conflict
    render(status: 409)
  end

  def unprocessable_entity
    render(status: 422)
  end

  def too_many_requests
    render(status: 429)
  end

  def internal_server_error
    render(status: 500)
  end

  def service_unavailable
    render(status: 503)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top; end

  def privacy_policy; end

  def terms_of_service; end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login; end

  def guest_login
    user = User.guest
    session[:user_id] = user.id
    redirect_to study_records_path
  end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  def send_custom_message
    user_id = params[:user_id] # LINEのユーザーIDを取得
    message = params[:message] # 送信するメッセージを取得
    
    response = LineBotService.send_message(user_id, message)
    
    if response.code == '200'
      render json: { status: 'success' }, status: :ok
    else
      render json: { status: 'error', message: response.body }, status: :internal_server_error
    end
  end
end

app/helpers/answer_index_helper.rb
module AnswerIndexHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_login_api_helper.rb
module LineLoginApiHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/setting_helper.rb
module SettingHelper
end

app/helpers/study_record_helper.rb
module StudyRecordHelper
end

app/helpers/study_time_helper.rb
module StudyTimeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja" prefix="og: http://ogp.me/ns#">
  <head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-MJYXL2Q9S6"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-MJYXL2Q9S6');
    </script>
    <title>LockInStudy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag('drone.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta property="og:title" content="勉強中の集中力持続を支援するアプリ | Lock In Study">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.lockinstudy.com">
    <meta property="og:image" content="https://www.lockinstudy.com/assets/drone-252925cc464ede0ae2993ca794a16ca04e2148a34ff0be86c979dfb780558b17.png">
    <meta name="twitter:card" content="summary">
    <meta property="og:site_name" content="Lock In Study">
    <meta property="og:description" content="勉強中に聞かれる質問に答えることで集中力を保ち、勉強内容の理解を深めることができるアプリです。">
  </head>

  <body>
  <% if logged_in? && !current_user.guest? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "ERROR" %></title>
  <%= stylesheet_link_tag 'error', media: 'all' %>
</head>
<body class="error_body">
  <!-- エラーメッセージやユーザーへの指示を含むページ固有のコンテンツ -->
  <%= yield %>
  <p class="top-page-link"><a href="/">ホームに戻る</a></p>
</body>
</html>

app/views/measure/measuring.html.erb
<main>
<section class="feature">
    <%= image_tag "drone.png", width:360, height:240 %>
    <h1><%= link_to 'スタート', "#", class: "start-button" %></h1>
    <!-- その他のコンテンツ -->
</section>
</main>

app/views/shared/_before_login_header.html.erb
<header>
<div class="header" id="header">
    <div class="logo"><%= link_to 'Lock In Study', root_path %></div>
    <% if current_user %>
      <div class= "guest-notice">ゲストユーザー使用中</div>
    <% end %>
    <div class="login"><%= link_to 'ログイン/会員登録', '/login' %></div>
</div>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div id="flash" class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <div class="footer" id="footer">
      <div class="terms"><%= link_to '利用規約', home_terms_of_service_path %></div>
      <div class="privacy"><%= link_to 'プライバシーポリシー', home_privacy_policy_path %></div>
      <div class="contact"><%= link_to 'お問い合わせ', 'https://forms.gle/eQrHeMtnV4kw7LcC7' %></div>
      <div id="page-top"><a href="#">Page Top</a></div>
    </div>
</footer>

app/views/shared/_header.html.erb
<div class="header" id="header">
  <div class="logo"><%= link_to 'Lock In Study', root_path %></div>
  <nav class="navigation">
    <%= link_to '測定', study_records_path %>
    <%= link_to '時間一覧', study_time_index_path %>
    <%= link_to '回答一覧', answer_index_index_path %>
    <%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete }  %>
  </nav>
</div>

app/views/shared/_line-bot-qr.html.erb
<div class="line-bot-qr">
  <p>このQRコードを読み込んだらLINEでの通知もできます。</p>
  <%= image_tag "line-bot-qr.png" %>
</div>