config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/privacy_policy', to: 'home#privacy_policy'
  get 'home/terms_of_service', to: 'home#terms_of_service'

  get 'line_login_api/login', to: 'line_login_api#login'
  get 'line_login_api/callback', to: 'line_login_api#callback'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "study_time/index" => "study_time#index"
  get 'answer_index/index' => 'answer_index#index'

  get "login" => "login#login"
  delete 'logout', to: 'setting#destroy', as: 'logout'

  # ゲストログイン
  post 'guest_login', to: 'login#guest_login'

  # LINE_message
  post 'send_custom_message', to: 'messages#send_custom_message'

  # get '/study_records' => 'study_records#index'
  resources :study_records, only: [:index] do
    member do
      patch :stop
    end
    collection do
      post :start
    end
  end
  resources :answers, only: [:new, :create]

    # カスタムエラーページ用のルート
    get '/400', to: 'errors#bad_request', as: :bad_request
    get '/401', to: 'errors#unauthorized', as: :unauthorized
    get '/403', to: 'errors#forbidden', as: :forbidden
    get '/404', to: 'errors#not_found', as: :not_found
    get '/409', to: 'errors#conflict', as: :conflict
    get '/422', to: 'errors#unprocessable_entity', as: :unprocessable_entity
    get '/429', to: 'errors#too_many_requests', as: :too_many_requests
    get '/500', to: 'errors#internal_server_error', as: :internal_server_error
    get '/503', to: 'errors#service_unavailable', as: :service_unavailable

  # すべての未知ルートを404
  match '*path', to: 'errors#not_found', via: :all

  # 開発環境でのみエラーページのプレビューを有効にする
  if Rails.env.development?
    get '/errors/:status', to: 'errors#show'
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  enum first_answer_choice: { study: 1, break: 2, other: 3 }

  validates :user_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/study_record.rb
class StudyRecord < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :answers
  has_many :study_records

  validates :line_user_id, presence: true, uniqueness: true
  validates :name, presence: true

  def self.guest
    find_or_create_by!(line_user_id: 'lis12345') do |user|
      user.name = "guest"
      user.is_guest = true
    end
  end 

  def guest?
    self.is_guest
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = initialize_answer_from_session
  end

  def create
    session[:answers] ||= {}
    session[:answers].merge!(answer_params.to_h)

    @answer = initialize_answer_from_session

    if @answer.valid?
      if final_question_answered?(@answer)
        @answer.save
        session.delete(:answers)
        render_final_message
      else
        @next_question = determine_next_question(@answer)
        render_next_question
      end
    else
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace("question_area", partial: "answers/form", locals: { answer: @answer }) }
        format.html { render :new }
      end
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:first_answer_choice, :second_answer, :third_answer)
  end

  def initialize_answer_from_session
    current_user.answers.build(session[:answers] || {})
  end

  def determine_next_question(answer)
    case answer.first_answer_choice
    when "study"
      if answer.second_answer.present?
        "それをする事で何を得ますか？"
      else
        "何の勉強をしていますか？"
      end
    when "break"
      "あと何分休憩しますか？"
    when "other"
      if answer.second_answer.present?
        "それをしたら何を失いますか？"
      else
        "何をしていますか？"
      end
    end
  end

  def render_next_question
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.update("question_area", partial: "answers/next_question", locals: { next_question: @next_question }) }
    end
  end

  def final_question_answered?(answer)
    p "final_question_answered?"
    case answer.first_answer_choice
    when 'study'
      answer.third_answer.present? # 「勉強」が選ばれた場合、third_answerが最後の質問になる
    when 'break'
      answer.second_answer.present? # 「休憩」が選ばれた場合、second_answerが最後の質問になる
    when 'other'
      answer.third_answer.present? # 「その他」が選ばれた場合、third_answerが最後の質問になる
    else
      false # それ以外の場合は、まだ最後の質問に到達していない
    end
  end

  def render_final_message
    respond_to do |format|
      format.turbo_stream do
        # 'question_area'を新しいフォームで置き換える
        render turbo_stream: turbo_stream.replace("question_area", partial: "answers/final_message")
      end
    end
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  layout 'error'

  def show
    status_code = params[:status] || 500
    render template: "errors/#{status_code}", status: status_code, layout: 'error'
  end

  def bad_request
    render(status: 400)
  end

  def unauthorized
    render(status: 401)
  end

  def forbidden
    render(status: 403)
  end

  def not_found
    render(status: 404)
  end

  def conflict
    render(status: 409)
  end

  def unprocessable_entity
    render(status: 422)
  end

  def too_many_requests
    render(status: 429)
  end

  def internal_server_error
    render(status: 500)
  end

  def service_unavailable
    render(status: 503)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top; end

  def privacy_policy; end

  def terms_of_service; end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login; end

  def guest_login
    user = User.guest
    session[:user_id] = user.id
    redirect_to study_records_path
  end
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  def send_custom_message
    user_id = params[:user_id] # LINEのユーザーIDを取得
    message = params[:message] # 送信するメッセージを取得
    
    response = LineBotService.send_message(user_id, message)
    
    if response.code == '200'
      render json: { status: 'success' }, status: :ok
    else
      render json: { status: 'error', message: response.body }, status: :internal_server_error
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def send_custom_message
    user_id = params[:user_id]
    message = params[:message]
    
    response = LineBotService.send_message(user_id, message)
    
    if response.code == '200'
      render json: { status: 'success' }, status: :ok
    else
      render json: { status: 'error', message: response.body }, status: :internal_server_error
    end
  end
end

app/controllers/setting_controller.rb
class SettingController < ApplicationController
  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end
end

app/helpers/answer_index_helper.rb
module AnswerIndexHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_login_api_helper.rb
module LineLoginApiHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/setting_helper.rb
module SettingHelper
end

app/helpers/study_record_helper.rb
module StudyRecordHelper
end

app/helpers/study_time_helper.rb
module StudyTimeHelper
end

app/views/home/privacy_policy.html.erb
<div class="privacy_wrapper">
  <h1 class="title">プライバシーポリシー</h1>
  <h3 class="subhead">はじめに</h3>
  <p class="content">
    Lock In Study（以下、「当社」とします）は、当社が運営するWebサービス（以下、「本サービス」とします）において、お客様のプライバシーを尊重し、
    お客様から提供される個人情報の保護に努めています。本プライバシーポリシーは、本サービスを利用される際に、当社がどのような情報を収集し、
    その情報をどのように扱うかについて説明しています。
  </p>
  <h3 class="subhead">取得する情報</h3>
  <p class="content">
    当社は、お客様から以下の情報を取得します。<br><br>
    ・氏名(ニックネームやペンネームも含む)<br>
    ・メールアドレス<br>
    ・外部サービスでお客様が利用するID、その他外部サービスのプライバシー設定によりお客様が連携先に開示を認めた情報<br>
    ・Cookie(クッキー)を用いて生成された識別情報<br>
    ・OSが生成するID、端末の種類、端末識別子等のお客様が利用するOSや端末に関する情報<br>
    ・当社ウェブサイトの滞在時間、入力履歴、購買履歴等の当社ウェブサイトにおけるお客様の行動履歴<br>
    ・当社アプリの起動時間、入力履歴、購買履歴等の当社アプリの利用履歴
  </p>
  <h3 class="subhead">情報を利用する目的</h3>
  <p class="content">
    当社は、お客様から取得した情報を、以下の目的のために利用します。<br><br>
    ・当社サービスに関する登録の受付、お客様の本人確認、認証のため<br>
    ・お客様の当社サービスの利用履歴を管理するため<br>
    ・当社サービスにおけるお客様の行動履歴を分析し、当社サービスの維持改善に役立てるため<br>
    ・お客様からのお問い合わせに対応するため<br>
    ・当社の規約や法令に違反する行為に対応するため<br>
    ・当社サービスの変更、提供中止、終了、契約解除をご連絡するため<br>
    ・当社規約の変更等を通知するため<br>
    ・以上の他、当社サービスの提供、維持、保護及び改善のため
  </p>
  <h3 class="subhead">安全管理のために講じた措置</h3>
  <p class="content">
    当社が、お客様から取得した情報に関して安全管理のために講じた措置につきましては、末尾記載のお問い合わせ先にご連絡をいただきましたら、
    法令の定めに従い個別にご回答させていただきます。
  </p>
  <h3 class="subhead">第三者提供</h3>
  <p class="content">
    当社は、お客様から取得する情報のうち、個人データ（個人情報保護法第１６条第３項）に該当するものついては、あらかじめお客様の同意を得ずに、
    第三者（日本国外にある者を含みます。）に提供しません。<br>
    但し、次の場合は除きます。<br><br>
    ・個人データの取扱いを外部に委託する場合<br>
    ・当社や当社サービスが買収された場合<br>
    ・事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）<br>
    ・その他、法律によって合法的に第三者提供が許されている場合
  </p>
  <h3 class="subhead">アクセス解析ツール</h3>
  <p class="content">
    当社は、お客様のアクセス解析のために、「Googleアナリティクス」を利用しています。Googleアナリティクスは、
    トラフィックデータの収集のためにCookieを使用しています。トラフィックデータは匿名で収集されており、個人を特定するものではありません。
    Cookieを無効にすれば、これらの情報の収集を拒否することができます。詳しくはお使いのブラウザの設定をご確認ください。
    Googleアナリティクスについて、詳しくは以下からご確認ください。<br><br>
    https://marketingplatform.google.com/about/analytics/terms/jp/
  </p>
  <h3 class="subhead">プライバシーポリシーの変更</h3>
  <p class="content">
    当社は、必要に応じて、このプライバシーポリシーの内容を変更します。この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。
  </p>
  <h3 class="subhead">お問い合わせ</h3>
  <p class="content">
    お客様の情報の開示、情報の訂正、利用停止、削除をご希望の場合は、以下の 「お問い合わせ」 よりご連絡ください。<br><br>
    <%= link_to "お問い合わせ", "https://forms.gle/eQrHeMtnV4kw7LcC7", class:"inquiry_button" %><br><br>
    この場合、必ず、運転免許証のご提示等当社が指定する方法により、ご本人からのご請求であることの確認をさせていただきます。
    なお、情報の開示請求については、開示の有無に関わらず、ご申請時に一件あたり1,000円の事務手数料を申し受けます。
  </p>
  <p class="content">
    2024年06月14日 制定
  </p>
</div>

app/views/home/top.html.erb
<div class="main-content">
  <%= image_tag "drone.png", width:430, height:240 %>
    <h1>あなたが集中して学習出来るように<br>サポートします</h1>
    <% if logged_in? && !current_user.guest? %>
      <%= button_to '測定', study_records_path, method: :get, class: 'try-button' %>
    <% else %>
      <%= button_to '使ってみる', guest_login_path, method: :post, class: 'try-button' %>
    <% end %>
    <div class="explanation">
      <div class="how_to_use">
        <h3>基本の使い方、今sourcetreeを使用してみた</h3>
        <p>
        ・スタートボタンを押して学習を開始<br>
        ・測定中に質問が投げかけられたら回答してください<br>
        ・勉強が完了したらストップボタンで測定終了
        </P>
        <%= image_tag "how_to_use.gif", width: '50%' %>
      </div>
      <div class="after_login">
        <h3>ログインすると</h3>
        <p>
          過去の勉強時間と回答の確認ができます。<br>
          勉強中の傾向の確認、改善に役立ちます。
        </P>
        <%= image_tag "after_login.gif", width: '50%' %>
      </div>
      <% if logged_in? && !current_user.guest? %>
      <div class="line_bot">
        <p>
          下のQRコードを読み込むと質問回答タイミングでLINEでの通知もできます。
        </p>
        <%= image_tag "line.jpeg", width: '25%' %>
        <%= image_tag "line_bot_qr.png", width: '20%' %>
      </div>
      <% end %>
    </div>
    <% if logged_in? && !current_user.guest? %>
      <%= button_to '測定', study_records_path, method: :get, class: 'try-button' %>
    <% else %>
      <%= button_to '使ってみる', guest_login_path, method: :post, class: 'try-button' %>
    <% end %>
</div>

app/views/login/login.html.erb
<div class="login-content">
  <%= link_to "LINEでログイン", line_login_api_login_path, class: "login-button" %>
</div>